=== identityxx/penrose-server/common/src/java/org/safehaus/penrose/directory/directory.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT directory (entry*)>

<!ELEMENT entry (entry-class?,description?,mapping-name?,oc*,at*,source*,aci*,parameter*,init?,add?,bind?,compare?,delete?,modify?,modrdn?,search?,unbind?,destroy?)>
<!ATTLIST entry dn CDATA "">
<!ATTLIST entry enabled CDATA #IMPLIED>
<!ATTLIST entry attached CDATA #IMPLIED>
<!ATTLIST entry id CDATA #IMPLIED>
<!ATTLIST entry parentId CDATA #IMPLIED>

<!ELEMENT init (#PCDATA)>
<!ELEMENT add (#PCDATA)>
<!ELEMENT bind (#PCDATA)>
<!ELEMENT compare (#PCDATA)>
<!ELEMENT delete (#PCDATA)>
<!ELEMENT modify (#PCDATA)>
<!ELEMENT modrdn (#PCDATA)>

<!ELEMENT search (#PCDATA)>
<!ATTLIST search filter CDATA #IMPLIED>

<!ELEMENT unbind (#PCDATA)>
<!ELEMENT destroy (#PCDATA)>

<!ELEMENT entry-class (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT mapping-name (#PCDATA)>

<!ELEMENT oc (#PCDATA)>

<!ELEMENT at (binary|constant|variable|expression)>
<!ATTLIST at name CDATA #REQUIRED>
<!ATTLIST at rdn (true|first|false) "false">
<!ATTLIST at operational (true|false) "false">

<!ELEMENT source (partition-name?,source-name?,mapping-name?,field*,parameter*)>
<!ATTLIST source alias CDATA #IMPLIED>
<!ATTLIST source name CDATA #IMPLIED>
<!ATTLIST source readOnly CDATA #IMPLIED>
<!ATTLIST source engine CDATA #IMPLIED>
<!ATTLIST source required CDATA #IMPLIED>
<!ATTLIST source add CDATA #IMPLIED>
<!ATTLIST source bind CDATA #IMPLIED>
<!ATTLIST source delete CDATA #IMPLIED>
<!ATTLIST source modify CDATA #IMPLIED>
<!ATTLIST source modrdn CDATA #IMPLIED>
<!ATTLIST source search CDATA #IMPLIED>
<!ELEMENT partition-name (#PCDATA)>
<!ELEMENT source-name (#PCDATA)>

<!ELEMENT field (binary|constant|variable|expression)>
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field primaryKey (true|first|false) "false">

<!ELEMENT binary (#PCDATA)>
<!ELEMENT constant (#PCDATA)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT expression (#PCDATA)>
<!ATTLIST expression foreach CDATA #IMPLIED>
<!ATTLIST expression var CDATA #IMPLIED>

<!ELEMENT aci (dn?,target?,attributes?,scope?,action?,permission)>
<!ATTLIST aci subject CDATA #IMPLIED>
<!ELEMENT dn (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT attributes (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT permission (#PCDATA)>

<!ELEMENT parameter (param-name, param-value)>
<!ELEMENT param-name (#PCDATA)>
<!ELEMENT param-value (#PCDATA)>

=== identityxx/penrose-server/samples/federation/templates/global/DIR-INF/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry dn="ou=Global,dc=Federation,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Global</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,ou=Global,dc=Federation,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,ou=Global,dc=Federation,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.DynamicEntry</entry-class>
    <mapping-name>virtual_users</mapping-name>
    <at name="uid" rdn="true">
      <variable>g.uid</variable>
    </at>
    <source alias="g" bind="sufficient">
      <partition-name>federation</partition-name>
      <source-name>users</source-name>
      <mapping-name>virtual_users_to_global_users</mapping-name>
      <field name="uid" primaryKey="true">
        <variable>rdn.uid</variable>
      </field>
    </source>
    <source alias="l" bind="sufficient">
      <partition-name>federation_ldap</partition-name>
      <source-name>users</source-name>
      <mapping-name>virtual_users_to_ldap_users</mapping-name>
      <field name="dn">
        <variable>g.seeAlso</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,ou=Global,dc=Federation,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,ou=Global,dc=Federation,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.DynamicEntry</entry-class>
    <mapping-name>virtual_groups</mapping-name>
    <at name="cn" rdn="true">
      <variable>g.primaryKey.cn</variable>
    </at>
    <source alias="g">
      <partition-name>federation</partition-name>
      <source-name>groups</source-name>
      <mapping-name>virtual_groups_to_global_groups</mapping-name>
      <field name="cn" primaryKey="true">
        <variable>rdn.cn</variable>
      </field>
    </source>
    <source alias="l">
      <partition-name>federation_ldap</partition-name>
      <source-name>groups</source-name>
      <mapping-name>virtual_groups_to_ldap_groups</mapping-name>
      <field name="dn">
        <variable>g.seeAlso</variable>
      </field>
    </source>
  </entry>

</directory>

=== identityxx/penrose-server/samples/ldif/DIR-INF/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry dn="dc=LDIF,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>LDIF</source-name>
    </source>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>uniqueMember</param-value>
    </parameter>
  </entry>

</directory>

=== identityxx/penrose-server/samples/ad_schema/DIR-INF/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry dn="dc=AD Schema,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>AD Schema</constant>
    </at>
    <at name="o">
      <constant>AD Schema</constant>
    </at>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="cn=AD Style,dc=AD Schema,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>ad_schema</source-name>
    </source>
  </entry>

  <entry dn="cn=LDAP Style,dc=AD Schema,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.activeDirectory.directory.ADSchemaEntry</entry-class>
    <oc>subentry</oc>
    <oc>subschema</oc>
    <oc>extensibleObject</oc>
    <at name="cn" rdn="true">
      <constant>LDAP Style</constant>
    </at>
    <source>
      <source-name>ldap_schema</source-name>
    </source>
  </entry>

</directory>

=== identityxx/penrose-server/conf/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry>
    <entry-class>org.safehaus.penrose.directory.RootEntry</entry-class>
    <oc>extensibleObject</oc>
    <at name="vendorName">
      <constant>${vendor.name}</constant>
    </at>
    <at name="vendorVersion">
      <constant>${product.title} Server ${product.version}</constant>
    </at>
    <at name="supportedLDAPVersion">
      <constant>3</constant>
    </at>
    <at name="subschemaSubentry">
      <constant>cn=Subschema</constant>
    </at>
    <at name="changelog">
      <constant>cn=changelog</constant>
    </at>
    <at name="namingContexts">
      <constant>dc=Example,dc=com</constant>
    </at>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="cn=Subschema">
    <entry-class>org.safehaus.penrose.schema.directory.SchemaEntry</entry-class>
    <oc>subentry</oc>
    <oc>subschema</oc>
    <oc>extensibleObject</oc>
    <at name="cn" rdn="true">
      <constant>Subschema</constant>
    </at>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="cn=Monitor">
    <entry-class>org.safehaus.penrose.monitor.directory.MonitorEntry</entry-class>
    <oc>monitorServer</oc>
    <at name="cn" rdn="true">
      <constant>Monitor</constant>
    </at>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>Example</constant>
    </at>
    <at name="o">
      <constant>Example</constant>
    </at>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="cn=Manager,dc=Example,dc=com">
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="cn" rdn="true">
      <constant>Manager</constant>
    </at>
    <at name="sn">
      <constant>Manager</constant>
    </at>
    <at name="userPassword">
      <constant>secret</constant>
    </at>
  </entry>

  <entry dn="ou=Users,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="ou=Groups,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

</directory>

=== identityxx/penrose-server/samples/ad_sync/DIR-INF/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry dn="dc=AD Sync,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>AD Sync</constant>
    </at>
    <at name="o">
      <constant>AD Sync</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=AD Sync,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>users_cache</source-name>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=AD Sync,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>groups_cache</source-name>
    </source>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>uniqueMember</param-value>
    </parameter>
  </entry>

</directory>

=== identityxx/penrose-server/samples/mysql/DIR-INF/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry dn="dc=MySQL,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>MySQL</constant>
    </at>
    <at name="o">
      <constant>MySQL</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=MySQL,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Users</constant>
    </at>
  </entry>

  <entry dn="uid=...,ou=Users,dc=MySQL,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.DynamicEntry</entry-class>
    <oc>person</oc>
    <oc>organizationalPerson</oc>
    <oc>inetOrgPerson</oc>
    <at name="uid" rdn="true">
      <variable>u.username</variable>
    </at>
    <at name="cn">
      <expression>
if (u == void || u == null) return null;
return u.firstName+" "+u.lastName;
      </expression>
    </at>
    <at name="sn">
      <variable>u.lastName</variable>
    </at>
    <at name="userPassword">
      <variable>u.password</variable>
    </at>
    <source alias="u">
      <source-name>users</source-name>
      <field name="username">
        <variable>uid</variable>
      </field>
      <field name="firstName">
        <expression>
if (cn == void || cn == null) return null;
int i = cn.lastIndexOf(" ");
if (i &lt; 0) return null;
return cn.substring(0, i);
        </expression>
      </field>
      <field name="lastName">
        <expression>
if (sn != void &amp;&amp; sn != null) return sn;
if (cn == void || cn == null) return null;
int i = cn.lastIndexOf(" ");
if (i &lt; 0) return cn;
return cn.substring(i+1);
        </expression>
      </field>
      <field name="password">
        <variable>userPassword</variable>
      </field>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=MySQL,dc=Example,dc=com">
    <oc>organizationalUnit</oc>
    <at name="ou" rdn="true">
      <constant>Groups</constant>
    </at>
  </entry>

  <entry dn="cn=...,ou=Groups,dc=MySQL,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.DynamicEntry</entry-class>
    <oc>groupOfUniqueNames</oc>
    <at name="cn" rdn="true">
      <variable>g.groupname</variable>
    </at>
    <at name="description">
      <variable>g.description</variable>
    </at>
    <source alias="g">
      <source-name>groups</source-name>
      <field name="groupname">
        <variable>cn</variable>
      </field>
      <field name="description">
        <variable>description</variable>
      </field>
    </source>
  </entry>

</directory>

=== identityxx/penrose-server/samples/proxy_subtree/DIR-INF/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry dn="dc=Proxy Subtree,dc=Example,dc=com">
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>Proxy Subtree</constant>
    </at>
    <at name="o">
      <constant>Proxy Subtree</constant>
    </at>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="ou=Users,dc=Proxy Subtree,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>users</source-name>
    </source>
  </entry>

  <entry dn="ou=Groups,dc=Proxy Subtree,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <source>
      <source-name>groups</source-name>
    </source>
    <parameter>
      <param-name>attributes</param-name>
      <param-value>uniqueMember</param-value>
    </parameter>
  </entry>

</directory>

=== identityxx/penrose-server/samples/lockout/DIR-INF/directory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE directory PUBLIC
  "-//Penrose/DTD Directory ${product.specification}//EN"
  "http://penrose.safehaus.org/dtd/directory.dtd">

<directory>

  <entry dn="dc=Lockout,dc=Example,dc=com">
    <entry-class>org.safehaus.penrose.directory.ProxyEntry</entry-class>
    <oc>dcObject</oc>
    <oc>organization</oc>
    <at name="dc" rdn="true">
      <constant>Lockout</constant>
    </at>
    <at name="o">
      <constant>Lockout</constant>
    </at>
    <source alias="LDAP">
      <source-name>LDAP</source-name>
    </source>
    <aci subject="self">
      <permission>rws</permission>
    </aci>
    <aci>
      <target>ATTRIBUTES</target>
      <attributes>userPassword</attributes>
      <action>deny</action>
      <permission>rs</permission>
    </aci>
    <aci>
      <permission>rs</permission>
    </aci>
  </entry>

  <entry dn="cn=lockout">
    <oc>extensibleObject</oc>
    <at name="cn" rdn="true">
      <constant>lockout</constant>
    </at>
  </entry>

  <entry dn="account=...,cn=lockout">
    <entry-class>org.safehaus.penrose.directory.DynamicEntry</entry-class>
    <oc>extensibleObject</oc>
    <at name="account" rdn="true">
      <variable>l.account</variable>
    </at>
    <at name="counter">
      <variable>l.counter</variable>
    </at>
    <at name="timestamp">
      <expression>
return org.safehaus.penrose.lockout.Lock.DATE_FORMAT.format(l.timestamp);
      </expression>
    </at>
    <source alias="l">
      <source-name>locks</source-name>
      <field name="account">
        <variable>account</variable>
      </field>
      <field name="counter">
        <variable>counter</variable>
      </field>
      <field name="timestamp">
        <expression>
return new java.sql.Timestamp(org.safehaus.penrose.lockout.Lock.DATE_FORMAT.parse(timestamp));
        </expression>
      </field>
    </source>
  </entry>

</directory>
